# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e9e1d1433735c009e7d41afcebc165bfdabe6641ac1f09f4de1293193860822108bfe7835908df743821510e0870d30e3dfeaf06442733b93f5854b3eae9f54e

test:
  secret_key_base: 785db87bd466089da29dac56bd8cc19e0d7bd9ae314a5c77e8320f79ed91bcc74c0f1b55f209aadbad484872555312277839b0833afb5b25e0b2ffb0922f4677

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
